name: Publish nuget package

on:
	push:
		branches:
			- main
		tags:
			- "v[0-9]+.[0-9]+.[0-9]+"

jobs:
	build:
		runs-on: ubuntu-latest
		timeout-minutes: 5

		steps:
			- name: Checkout
			  uses: actions/checkout@v2
			  with:
			  fetch-depth: 0
			- name: Verify commit exists
			  run: git branch --remote --contains | grep origin/main
			- name: Extract relse notes
			  run: |
					git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES
			- name: Set Version from tag
			  run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV