name: Publish CQRS nuget package

on:
  push:
    branches: [ main ]
    tags:
      - v*

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        env:
            APIKEY: ${{secrets.NUGETAPIKEY}}
            Configuration: DependencyInjection

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Verify commit exists on main branch
              run: git branch --remote --contains | grep origin/main
            - name: Set VERSION variable from tag
              run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            - name: Install dependencies
              run: dotnet restore
            - name: Build Dependency injection package
              run: dotnet build --configuration ${{Configuration}} --no-restore
            - name: Pack Dependency injection library
              run: dotnet pack --configuration ${{Configuration}} --no-restore /p:Version=${VERSION} --no-build --output .
            #- name: Push nuget package
            #  run: dotnet nuget push VDsoft.${{Configuration}}.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${APIKEY}